### PR TITLE
Introduce jenkins_plugins_retries var

### PR DESCRIPTION
**Pull request by kremers**

### CODE REVIEW

**Comment by karlmdavis** [comment]
@kremers Could you merge or rebase this to latest? Would like to see it passing the tests.

**Comment by karlmdavis** [comment]
Also, could you please give me permission to edit this branch/PR? Just want to tweak the docs a bit, because I'm OCD like that.

(And, by the way, thanks very much for this change, also!)

**Comment by kremers** [comment]
I'll do asap

**Comment by kremers** [comment]
Rebased and added you as collaborator to my repo so you should be able to edit all branches.

**Pull request merged**
